version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11  # or corretto8, openjdk11 — depending on your need
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Cleaning up previous builds...
      - mvn clean

  build:
    commands:
      - echo Building Java WAR application...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Build completed at `date`
      - echo Copying WAR file to output directory...
      - mkdir -p output
      - cp target/*.war output/

artifacts:
  files:
    - output/**/*
    - appspec.yml
    - scripts/**/*
  discard-paths: no
